### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by Starraider** [mandrasch/ddev-typo3-vite-svelte#1]
Hi!
I followed exactly the installation process, which you have described in the README.md.
So far everything looks great. If I start the local vite server with ```ddev npm run dev``` or ```ddev vite-serve start``` the vite server seems to listening and the svelte-demo-block is shown correctly. But no matter what I change in the Test.svelte file, after saving, the frontend doesn't update. Only after restarting the vite-server, the changes are visible in the frontend.
So the Hot Module Replacement (HMR) doesn't seem to work and I have no idea why!
Any ideas, what I'm doing wrong?

Btw.: I tried fgeierst/typo3-vite-demo as well and there it works perfectly - but I would prefere svelte instead of vue.

**Comment by mandrasch** [comment]
Hi @Starraider, nice that you give this a run! High five for Svelte! 👍😎

I'll check my own local dev instance in the next days, hacked this together rather quickly. 

Could you provide some more infos in the meantime? 

- operating system
- DDEV version (ddev -v) 
- path where .svelte File is located (if you changed it)

Maybe the paths are not picked up correctly. 

(If all fails we could also reach out to @fgeierst. And there is also a new typo3 vite extension in the making)

Cheers!

**Comment by mandrasch** [comment]
Works for me on `ddev version v1.21.4`, browsers Chrome and Firefox, command `ddev npm run dev`.

Please restart your container with `ddev restart` and only use `ddev npm run dev` - does it still not work? 🤔 

Do you see any errors in Chrome or Firefox devtools?

**Comment by mandrasch** [comment]
Update: Just noticed that I left this line in vite.config.js marked with a TODO:

`origin: 'https://ddev-typo3-vite-svelte.ddev.site' // TODO: is this necessary?`

fgeierst left this empty (`origin:''`) in his repository, maybe this is causing it. I'll investigate.

**Comment by mandrasch** [comment]
I pushed a small fix to `vite.config.js`, but that was not a real problem.

Additional question to those questions above: 

Did you change the project title or is your site URL https://ddev-typo3-vite-svelte.ddev.site/ as well?

**Comment by Starraider** [comment]
Hi!
I restarted everything multiple times - HMR still not working.
I use: 
MacBook Air with macOS Venture v13.3.1 and DDEV v1.21.6.
I didn't change anything - just cloned the repo, followed the installation in README and tried it out. 
I tried it with Safari, Firefox and Chrome.
When I change the css or html in Test.svelte it doesn't update the browser.

PS: I can't see your fix to vite.config.js. Did you push it to github?

**Comment by mandrasch** [comment]
Forgot to push indeed, just changed origin to: 

        origin: ''

Thanks for infos! I'll re-check with latest ddev on my machine and get back to you 👍

**Comment by Starraider** [comment]
Hi!
I solved the problem!
In .ddev/config.yaml I switched on mutagen and restarted DDEV:
```mutagen_enabled: true```
Now it's working perfect.
Thanks for your work!

**Comment by fgeierst** [comment]
Hi Sven, glad you found the solution! 

By the way, you can of course use https://github.com/fgeierst/typo3-vite-demo with Svelte, too. Just uninstall vue and add svelte with `pnpm add svelte && pnpm add -D @sveltejs/vite-plugin-svelte` and adapt the vite config file according to https://github.com/sveltejs/vite-plugin-svelte.

**Comment by mandrasch** [comment]
Thanks for report, @Starraider! Glad it is working again. 🎉 

(Kind of wondering why it doesn't work without Mutagen though. 🤔 

- I had mutagen disabled globally in `~/.ddev/global_config.yaml`, worked as well with `v.1.21.6`
- Enabled mutagen globally, also worked with the current config.yaml

I'm still on OSX 12.6 Monterey, only difference I see so far. Interesting!)
